version: '{build}'

image: Visual Studio 2019

environment:
  matrix:

    - compiler: msvc-16-seh
      generator: "Visual Studio 16 2019"
      genarch: -A Win32
      configuration: Debug

    - compiler: msvc-16-seh
      generator: "Visual Studio 16 2019"
      genarch: -A x64
      configuration: Debug

    - compiler: msvc-16-seh
      generator: "Visual Studio 16 2019"
      genarch: -A Win32
      configuration: Release

    - compiler: msvc-16-seh
      generator: "Visual Studio 16 2019"
      genarch: -A x64
      configuration: Release


    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
      compiler: msvc-15-seh
      generator: "Visual Studio 15 2017"
      configuration: Debug

    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
      compiler: msvc-15-seh
      generator: "Visual Studio 15 2017 Win64"
      configuration: Debug

    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
      compiler: msvc-15-seh
      generator: "Visual Studio 15 2017"
      configuration: Release

    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
      compiler: msvc-15-seh
      generator: "Visual Studio 15 2017 Win64"
      configuration: Release


    #- APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
    #  compiler: msvc-14-seh
    #  generator: "Visual Studio 14 2015"
    #  configuration: Debug

    #- APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
    #  compiler: msvc-14-seh
    #  generator: "Visual Studio 14 2015 Win64"
    #  configuration: Debug

    #- APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
    #  compiler: msvc-14-seh
    #  generator: "Visual Studio 14 2015"
    #  configuration: Release

    #- APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
    #  compiler: msvc-14-seh
    #  generator: "Visual Studio 14 2015 Win64"
    #  configuration: Release


    #- compiler: gcc-5.3.0-posix
    #  generator: "MinGW Makefiles"
    #  cxx_path: 'C:\mingw-w64\i686-5.3.0-posix-dwarf-rt_v4-rev0\mingw32\bin'
    #  APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
    #  configuration: Quicktest
    #  externconfig: Debug
    #  cmkargs: "-DC4STL_PEDANTIC=ON -DC4STL_WERROR=ON"

matrix:
  fast_finish: true

install:
  - git submodule update --init --recursive
  # git bash conflicts with MinGW makefiles
  - set "PATH=%PATH:C:\Program Files\Git\usr\bin;=%"
  - if not "%cxx_path%"=="" (set "PATH=%PATH%;%cxx_path%")
  - cmake --version

build_script:
  - md _build_static
  - md _build_shared
  - md _extern
  - echo %generator%
  - echo %genarch%
  - echo %configuration%
  - set C4_EXTERN_DIR=_extern
  - set NUM_JOBS=3
  - cmake -S .. -B _build_static -DRYML_DEV=ON -DRYML_TEST_SUITE=ON -G "%generator%" %genarch% "-DCMAKE_BUILD_TYPE=%configuration%" "-DCMAKE_INSTALL_PREFIX=../_install_static" -DBUILD_SHARED_LIBS=OFF
  - cmake -S .. -B _build_shared -DRYML_DEV=ON -DRYML_TEST_SUITE=ON -G "%generator%" %genarch% "-DCMAKE_BUILD_TYPE=%configuration%" "-DCMAKE_INSTALL_PREFIX=../_install_shared" -DBUILD_SHARED_LIBS=ON
  - cmake --build _build_static --config %configuration% --target test-build --parallel %NUM_JOBS%
  - cmake --build _build_static --config %configuration% --target test-build --parallel %NUM_JOBS%

test_script:
  - cmake --build _build_shared --config %configuration% --target test
  - cmake --build _build_shared --config %configuration% --target test

artifacts:
  - path: '_build/CMakeFiles/*.log'
    name: logs
  - path: '_build/Testing/**/*.xml'
    name: test_results

skip_commits:
  files:
    - .gitignore
    - .travis*
    - .ci/travis*
    - .ci/dev_*
    - .ci/show_*
    - .ci/vagrant*
    - .ci/Vagrant*
    - bm/html/*
    - doc/*
    - LICENSE.txt
    - README.*
